#pragma once

#include "AnalogNoiseFilter.h"
#include "BlurFilter.h"
#include "CircleMaskFilter.h"
#include "ColorNoiseFilter.h"
#include "DigitalNoiseFilter.h"
#include "EdgeFilter.h"
#include "MaruFilter.h"
#include "MaskFilter.h"
#include "OrbitalFilter.h"
#include "ScanLineFilter.h"
#include "ScanLineNoiseFilter.h"
#include "SciFiFilter.h"
#include "ScrollFilter.h"
#include "SplitFilter.h"
#include "ThresholdFilter.h"